In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("hotels_RoomPrice.csv")
df2 = pd.read_csv("Hotel_Room_attributes.csv")

df_merge1 = df1.merge(df2, left_on = 'hotelcode', right_on = 'hotelcode')

# c = pd.read_csv("hotel_price_min_max - Formula.csv")
# d = pd.read_csv("hotels_RoomPrice.csv")

In [3]:
df_merge1

,id_x,refid,hotelcode,websitecode,ratedate,los,guests,roomtype_x,onsiterate,netrate,...,proxyused,israteperstay,mealinclusiontype,hotelblock,input_dtcollected,Unnamed: 29,id_y,roomamenities_y,roomtype_y,ratedescription_y
0,50677497,8646773,634876,5,02/11/19,1,1,Double Room,82.36,87.84,...,media:M3diAproxy@173.44.165.126:80,Y,Free Breakfast,NaN,13/10/19,NaN,50677497,Air conditioning: ;Alarm clock: ;Carpeting: ;C...,Double Room,"Room size: 15 m²/161 ft², Shower, 1 king bed"
1,50677497,8646773,634876,5,02/11/19,1,1,Double Room,82.36,87.84,...,media:M3diAproxy@173.44.165.126:80,Y,Free Breakfast,NaN,13/10/19,NaN,50677498,Air conditioning: ;Alarm clock: ;Carpeting: ;C...,Double Room,"Room size: 15 m²/161 ft², Shower, 1 king bed"
2,50677497,8646773,634876,5,02/11/19,1,1,Double Room,82.36,87.84,...,media:M3diAproxy@173.44.165.126:80,Y,Free Breakfast,NaN,13/10/19,NaN,50677499,Air conditioning: ;Alarm clock: ;Carpeting: ;C...,Deluxe Double Room with Shower,"Room size: 17 m²/183 ft², Shower, 1 queen bed ..."
3,50677497,8646773,634876,5,02/11/19,1,1,Double Room,82.36,87.84,...,media:M3diAproxy@173.44.165.126:80,Y,Free Breakfast,NaN,13/10/19,NaN,50731279,Air conditioning: ;Alarm clock: ;Carpeting: ;C...,Superior Double Room,"Room size: 17 m²/183 ft², Shower, 1 double bed"
4,50677497,8646773,634876,5,02/11/19,1,1,Double Room,82.36,87.84,...,media:M3diAproxy@173.44.165.126:80,Y,Free Breakfast,NaN,13/10/19,NaN,63480999,Air conditioning: ;Alarm clock: ;Carpeting: ;C...,Standard Double or Twin Room,"Room size: 13 m²/140 ft², Shower, 1 queen bed ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9032756,88475970,8022722,6592926,5,17/10/19,1,1,"1 Double Bed, 1 Single Bed, standard room",0.00,0.00,...,media:M3diAproxy@209.242.221.93:80,N,NaN,Sold out,13/10/19,NaN,88475966,Air conditioning: ;Dressing room: ;Free Wi-Fi ...,Standard Twin Room,"Room size: 16 m²/172 ft², 2 single beds"
9032757,88475970,8022722,6592926,5,17/10/19,1,1,"1 Double Bed, 1 Single Bed, standard room",0.00,0.00,...,media:M3diAproxy@209.242.221.93:80,N,NaN,Sold out,13/10/19,NaN,88475967,Air conditioning: ;Free Wi-Fi in all rooms!: ;...,"1 Double Bed, standard room","Room size: 20 m²/215 ft², Balcony/terrace, 1 d..."
9032758,88475970,8022722,6592926,5,17/10/19,1,1,"1 Double Bed, 1 Single Bed, standard room",0.00,0.00,...,media:M3diAproxy@209.242.221.93:80,N,NaN,Sold out,13/10/19,NaN,88475968,Air conditioning: ;Free Wi-Fi in all rooms!: ;...,"1 Double Bed, standard room","Room size: 20 m²/215 ft², Balcony/terrace, 1 d..."
9032759,88475970,8022722,6592926,5,17/10/19,1,1,"1 Double Bed, 1 Single Bed, standard room",0.00,0.00,...,media:M3diAproxy@209.242.221.93:80,N,NaN,Sold out,13/10/19,NaN,88475969,Air conditioning: ;Free Wi-Fi in all rooms!: ;...,"2 Single Beds, standard room","Room size: 20 m²/215 ft², 2 single beds"
9032760,88475970,8022722,6592926,5,17/10/19,1,1,"1 Double Bed, 1 Single Bed, standard room",0.00,0.00,...,media:M3diAproxy@209.242.221.93:80,N,NaN,Sold out,13/10/19,NaN,88475970,NaN,"1 Double Bed, 1 Single Bed, standard room",NaN

**NOTE:**
I think this data should be enough for the project.
i tried to merge all the .csv's but it not working properly ie;Data is not connected correctly  so, im thinking this should be fine.

In [8]:
df_merge1.to_csv("df_out1.csv", index= False )

In [ ]:
df3 = pd.read_csv("Hotel_details.csv")
# df3 = pd.read_csv("hotel_price_min_max - Formula.csv")

df_merge2 = df_merge1.merge(df3, left_on = 'hotelcode', right_on = 'hotelcode')

In [ ]:
df_merge2.to_csv("df_OutFinal.csv", index= False )